[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "widpy"
dynamic = ["version"]
description = 'Parse WISEDash Public data files into a local database of school outcomes'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Ben Taft", email = "ben.taft@career2cradle.org" },
  { name = "Higher Expectations for Racine County"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "sqlalchemy"
]

[project.urls]
Documentation = "https://github.com/Ben Taft/widpy#readme"
Issues = "https://github.com/Ben Taft/widpy/issues"
Source = "https://github.com/Ben Taft/widpy"

[tool.hatch.version]
path = "src/widpy/__about__.py"

[tool.hatch.env]
dirs = [".venv"]

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/widpy tests}"

[tool.coverage.run]
source_pkgs = ["widpy", "tests"]
branch = true
parallel = true
omit = [
  "src/widpy/__about__.py",
]

[tool.coverage.paths]
widpy = ["src/widpy", "*/widpy/src/widpy"]
tests = ["tests", "*/widpy/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
